apiVersion: apps/v1
kind: Deployment
metadata:
  name: mounika-deployment
  labels:
    app: mounika-tut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mounika-tut
  template:
    metadata:
      labels:
        app: mounika-tut
    spec:
      containers:
        - name: mounika-tut
          image: demaksac.azurecr.io/mounilebakstutorial:36
          ports:
            - containerPort: 80



apiVersion: v1
kind: Service
metadata:
  name: mounika-tut-loadbalancer-service
  labels:
    app: mounika-tut
spec:
  type: LoadBalancer
  selector:
    app: mounika-tut
  ports:
    - port: 80
      targetPort: 80
  ports:
    - port: 80
      targetPort: 80
